/**
 * 飞书消息 reaction 合法值。
 * 来源：飞书开放平台「表情文案说明」
 * https://open.feishu.cn/document/server-docs/im-v1/message-reaction/emojis-introduce?lang=zh-CN
 * 拉取日期：2026-04-14
 */
export const FEISHU_REACTION_TYPES = [
  "OK",
  "THUMBSUP",
  "THANKS",
  "MUSCLE",
  "FINGERHEART",
  "APPLAUSE",
  "FISTBUMP",
  "JIAYI",
  "DONE",
  "SMILE",
  "BLUSH",
  "LAUGH",
  "SMIRK",
  "LOL",
  "FACEPALM",
  "LOVE",
  "WINK",
  "PROUD",
  "WITTY",
  "SMART",
  "SCOWL",
  "THINKING",
  "SOB",
  "CRY",
  "ERROR",
  "NOSEPICK",
  "HAUGHTY",
  "SLAP",
  "SPITBLOOD",
  "TOASTED",
  "GLANCE",
  "DULL",
  "INNOCENTSMILE",
  "JOYFUL",
  "WOW",
  "TRICK",
  "YEAH",
  "ENOUGH",
  "TEARS",
  "EMBARRASSED",
  "KISS",
  "SMOOCH",
  "DROOL",
  "OBSESSED",
  "MONEY",
  "TEASE",
  "SHOWOFF",
  "COMFORT",
  "CLAP",
  "PRAISE",
  "STRIVE",
  "XBLUSH",
  "SILENT",
  "WAVE",
  "WHAT",
  "FROWN",
  "SHY",
  "DIZZY",
  "LOOKDOWN",
  "CHUCKLE",
  "WAIL",
  "CRAZY",
  "WHIMPER",
  "HUG",
  "BLUBBER",
  "WRONGED",
  "HUSKY",
  "SHHH",
  "SMUG",
  "ANGRY",
  "HAMMER",
  "SHOCKED",
  "TERROR",
  "PETRIFIED",
  "SKULL",
  "SWEAT",
  "SPEECHLESS",
  "SLEEP",
  "DROWSY",
  "YAWN",
  "SICK",
  "PUKE",
  "BETRAYED",
  "HEADSET",
  "EatingFood",
  "MeMeMe",
  "Sigh",
  "Typing",
  "Lemon",
  "Get",
  "LGTM",
  "OnIt",
  "OneSecond",
  "VRHeadset",
  "YouAreTheBest",
  "SALUTE",
  "SHAKE",
  "HIGHFIVE",
  "UPPERLEFT",
  "ThumbsDown",
  "SLIGHT",
  "TONGUE",
  "EYESCLOSED",
  "RoarForYou",
  "CALF",
  "BEAR",
  "BULL",
  "RAINBOWPUKE",
  "ROSE",
  "HEART",
  "PARTY",
  "LIPS",
  "BEER",
  "CAKE",
  "GIFT",
  "CUCUMBER",
  "Drumstick",
  "Pepper",
  "CANDIEDHAWS",
  "BubbleTea",
  "Coffee",
  "Yes",
  "No",
  "OKR",
  "CheckMark",
  "CrossMark",
  "MinusOne",
  "Hundred",
  "AWESOMEN",
  "Pin",
  "Alarm",
  "Loudspeaker",
  "Trophy",
  "Fire",
  "BOMB",
  "Music",
  "XmasTree",
  "Snowman",
  "XmasHat",
  "FIREWORKS",
  "2022",
  "REDPACKET",
  "FORTUNE",
  "LUCK",
  "FIRECRACKER",
  "StickyRiceBalls",
  "HEARTBROKEN",
  "POOP",
  "StatusFlashOfInspiration",
  "18X",
  "CLEAVER",
  "Soccer",
  "Basketball",
  "GeneralDoNotDisturb",
  "Status_PrivateMessage",
  "GeneralInMeetingBusy",
  "StatusReading",
  "StatusInFlight",
  "GeneralBusinessTrip",
  "GeneralWorkFromHome",
  "StatusEnjoyLife",
  "GeneralTravellingCar",
  "StatusBus",
  "GeneralSun",
  "GeneralMoonRest",
  "MoonRabbit",
  "Mooncake",
  "JubilantRabbit",
  "TV",
  "Movie",
  "Pumpkin",
  "BeamingFace",
  "Delighted",
  "ColdSweat",
  "FullMoonFace",
  "Partying",
  "GoGoGo",
  "ThanksFace",
  "SaluteFace",
  "Shrug",
  "ClownFace",
  "HappyDragon",
] as const;

export type FeishuReactionType = (typeof FEISHU_REACTION_TYPES)[number];

const FEISHU_REACTION_TYPE_SET = new Set<string>(FEISHU_REACTION_TYPES);

export function isValidFeishuReactionType(value: string): value is FeishuReactionType {
  return FEISHU_REACTION_TYPE_SET.has(value);
}

export function sanitizeFeishuReactionType(
  value?: string | null
): FeishuReactionType | undefined {
  const trimmed = value?.trim();
  if (!trimmed) return undefined;
  return isValidFeishuReactionType(trimmed) ? trimmed : undefined;
}
